"""add unique contrantic colaborador(cinema_id, usuario_id)

Revision ID: a512b5f15cc0
Revises: abd30ccc2b5b
Create Date: 2023-12-09 23:56:01.627236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a512b5f15cc0'
down_revision: Union[str, None] = 'abd30ccc2b5b'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_usuario_cinema', 'Colaborador', ['usuario_id', 'cinema_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_usuario_cinema', 'Colaborador', type_='unique')
    # ### end Alembic commands ###
