"""init db

Revision ID: abd30ccc2b5b
Revises: 
Create Date: 2023-12-09 20:53:29.081811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abd30ccc2b5b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ('default',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cinema',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('is_ativo', sa.Boolean(), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('rua', sa.String(length=100), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Filme',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('is_ativo', sa.Boolean(), nullable=False),
    sa.Column('dt_criado', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Usuario',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('is_ativo', sa.Boolean(), nullable=False),
    sa.Column('dt_criado', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Colaborador',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('cinema_id', sa.String(length=36), nullable=False),
    sa.Column('is_ativo', sa.Boolean(), nullable=False),
    sa.Column('dt_criado', sa.DateTime(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cinema_id'], ['Cinema.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Sala',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('is_ativo', sa.Boolean(), nullable=False),
    sa.Column('cinema_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['cinema_id'], ['Cinema.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Assento',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assento', sa.String(length=50), nullable=False),
    sa.Column('is_ativo', sa.Boolean(), nullable=False),
    sa.Column('sala_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['sala_id'], ['Sala.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assento', 'sala_id', name='uq_assento_sala')
    )
    op.create_table('Sessao',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dt_inicio', sa.DateTime(), nullable=False),
    sa.Column('dt_fim', sa.DateTime(), nullable=False),
    sa.Column('sala_id', sa.String(length=36), nullable=False),
    sa.Column('filme_id', sa.String(length=36), nullable=False),
    sa.Column('dt_criado', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['filme_id'], ['Filme.id'], ),
    sa.ForeignKeyConstraint(['sala_id'], ['Sala.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sessao_id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('assento_id', sa.String(length=36), nullable=False),
    sa.Column('is_cancelado', sa.Boolean(), nullable=False),
    sa.Column('is_usado', sa.Boolean(), nullable=False),
    sa.Column('dt_criado', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assento_id'], ['Assento.id'], ),
    sa.ForeignKeyConstraint(['sessao_id'], ['Sessao.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    op.drop_table('Sessao')
    op.drop_table('Assento')
    op.drop_table('Sala')
    op.drop_table('Colaborador')
    op.drop_table('Usuario')
    op.drop_table('Filme')
    op.drop_table('Cinema')
    # ### end Alembic commands ###
